name: Build and Push Docker Image

on:
  push:

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Set short git commit SHA
        id: vars
        run: |
          short_sha=$(git rev-parse --short ${{ github.sha }})
          echo "short_sha=$short_sha" >> "$GITHUB_OUTPUT"
          
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: |
            scriptcoded/j26-usher:latest
            scriptcoded/j26-usher:${{ steps.vars.outputs.short_sha }}
